services:
  pgsql:
    image: postgres:18-alpine
    container_name: makan-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: makan
      POSTGRES_DB: makan
    volumes:
      - makan-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U makan -d makan"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: makan-redis
    ports:
      - "6379:6379"
    volumes:
      - makan-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  makan-postgres-data:
    driver: local
  makan-redis-data:
    driver: local
